### PR TITLE
TM-97 implement vuex store

### PR DESCRIPTION
**Pull request by janoliver20**
Implemented open-api-client stubs
Implemented Vuex Store
Implemented UI:
- created component to create Vocabs and Entities
- Created component to list Vocabs and Entities
Connected UI to logic

Closes TM-97, TM-98

### CODE REVIEW

**Review by ja-fra — APPROVED** [review]
LGTM - with my limited vue-knowledge...

**Comment by ManuelTS** [comment]
@ja-fra Same here, but have you started and clicked through the FE? Is it ok this way for you?

**Review by ja-fra — CHANGES_REQUESTED** [review]
> @ja-fra Same here, but have you started and clicked through the FE? Is it ok this way for you?

There's not much yet to see, but: I've noticed that the requests to the backend target the full-qualified url... please use relative URL (`./api/v1`) as baseUrl.

**Review by ManuelTS — CHANGES_REQUESTED** [review]
Please add screen shots showing:

- The looks of the entity and vocabulary lists
- The looks of the single image- or text buttons of single entities and vocabularies of all the supported REST actions of the BE

**Comment by janoliver20** [comment]
@ja-fra openAPI already generates it like that, I can not change anything there

@ManuelTS 
Here are screenshots with examples: 

Screenshot 2021-12-13 at 08 28 50
Screenshot 2021-12-13 at 08 28 46
Screenshot 2021-12-13 at 08 28 37
Screenshot 2021-12-13 at 08 28 29

**Comment by ja-fra** [comment]
> @ja-fra openAPI already generates it like that, I can not change anything there

At least in `VocabularyService` and `EntityService` there are settings like
```
  private readonly basePath: string;
￼  private readonly apiPath: string;
```
IMHO that's the place to patch in...

**Comment by janoliver20** [comment]
@ja-fra Changed the path to a relative path

**Review by ja-fra — APPROVED** [review]

**Review by ManuelTS — APPROVED** [review]

**Pull request merged**
